
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]] #mandatory
modId="picasso_palace"
version="0.1-1.20.1"
displayName="Picasso Palace"
authors="Fermine"
description='''A painting hopping adventure'''
mod_group_id="com.fermine.picasso_palace"
mapping_channel="parchment"
mapping_version="2023.09.03-1.20.1"
